version: '3.8'

services:
  value-seeker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: value-seeker-app
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./deploy:/app/deploy
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - LOG_LEVEL=INFO
      - DEBUG_MODE=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加监控服务
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: value-seeker-prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: value-seeker-grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-storage:/var/lib/grafana

# volumes:
#   grafana-storage: